### ISSUE TITLE
How to install and use, my friend?

### ISSUE THREAD

**Issue by switecandy** [AliKarami/speed-trader#1]

**Comment by AliKarami** [comment]
Hi my friend, I highly recommend to not use this app yet, because it's just at the beginning of the development road.
I added `How to Setup` section in the readme but I do not suggest to use it as your production trader.
Instead, you can use at as experimental trader in `TEST=true` environment and collaborate and contribute to reaching to stable release sooner.

**Comment by AliKarami** [comment]
Please wait for Stable Release
